"""Grad-CAM style explainability for the U-Net segmentation model."""

from __future__ import annotations

from dataclasses import dataclass

import torch
import torch.nn.functional as F
from torch import nn


@dataclass(frozen=True)
class GradCAMResult:
    """Store the main tensors generated by the Grad-CAM pass."""

    logits: torch.Tensor
    probabilities: torch.Tensor
    predicted_mask: torch.Tensor
    confidence: float
    heatmap: torch.Tensor


class SegmentationGradCAM:
    """Compute an activation heatmap for a binary segmentation model."""

    def __init__(self, model: nn.Module, target_layer: nn.Module | None = None):
        """Attach hooks to the selected feature layer."""
        self.model = model
        self.target_layer = target_layer or self._resolve_default_layer(model)
        self.activations: torch.Tensor | None = None
        self.gradients: torch.Tensor | None = None
        self._hook_handle = self.target_layer.register_forward_hook(
            self._forward_hook
        )

    def _resolve_default_layer(self, model: nn.Module) -> nn.Module:
        """Choose the bottleneck block of the U-Net as the explanation layer."""
        if hasattr(model, "down4") and isinstance(getattr(model, "down4"), nn.Module):
            return getattr(model, "down4")

        last_module = model
        for module in model.modules():
            if module is not model and isinstance(module, nn.Module):
                last_module = module
        return last_module

    def _forward_hook(
        self,
        module: nn.Module,
        inputs,
        output,
    ) -> None:
        """Capture activations and attach a hook to store gradients."""
        self.activations = output
        if isinstance(output, torch.Tensor) and output.requires_grad:
            output.register_hook(self._save_gradient)

    def _save_gradient(self, gradient: torch.Tensor) -> torch.Tensor:
        """Persist gradients from the target layer."""
        self.gradients = gradient
        return gradient

    def _compute_target_score(
        self,
        probabilities: torch.Tensor,
        predicted_mask: torch.Tensor,
    ) -> torch.Tensor:
        """Reduce segmentation probabilities to one scalar score."""
        positive_values = probabilities[predicted_mask > 0]
        if positive_values.numel() > 0:
            return positive_values.mean()
        return probabilities.max()

    def _build_heatmap(self, target_size: tuple[int, int]) -> torch.Tensor:
        """Build a normalized Grad-CAM heatmap."""
        if self.activations is None or self.gradients is None:
            raise RuntimeError("Grad-CAM hooks did not capture activations.")

        activations = self.activations
        gradients = self.gradients
        if activations.dim() == 3:
            activations = activations.unsqueeze(0)
        if gradients.dim() == 3:
            gradients = gradients.unsqueeze(0)

        weights = gradients.mean(dim=(2, 3), keepdim=True)
        heatmap = torch.sum(weights * activations, dim=1)
        heatmap = torch.relu(heatmap)
        heatmap = F.interpolate(
            heatmap.unsqueeze(1),
            size=target_size,
            mode="bilinear",
            align_corners=False,
        ).squeeze(1)

        heatmap = heatmap - heatmap.min()
        maximum = heatmap.max()
        if maximum > 0:
            heatmap = heatmap / maximum
        return heatmap.squeeze(0).detach().cpu()

    def generate(self, input_tensor: torch.Tensor) -> GradCAMResult:
        """Run the model, backpropagate a foreground score, and build heatmap."""
        if input_tensor.dim() != 4 or input_tensor.size(0) != 1:
            raise ValueError("Grad-CAM expects a single image tensor with shape (1, C, H, W).")

        self.model.zero_grad(set_to_none=True)
        self.activations = None
        self.gradients = None

        with torch.enable_grad():
            logits = self.model(input_tensor)
            probabilities = torch.sigmoid(logits)
            predicted_mask = (probabilities >= 0.5).float()
            confidence = float(
                probabilities[predicted_mask > 0].mean().item()
                if (predicted_mask > 0).any()
                else probabilities.max().item()
            )
            target_score = self._compute_target_score(probabilities, predicted_mask)
            target_score.backward()

        heatmap = self._build_heatmap(input_tensor.shape[-2:])
        self.model.zero_grad(set_to_none=True)
        return GradCAMResult(
            logits=logits.detach(),
            probabilities=probabilities.detach(),
            predicted_mask=predicted_mask.detach(),
            confidence=confidence,
            heatmap=heatmap,
        )

    def close(self) -> None:
        """Release the registered hook."""
        if self._hook_handle is not None:
            self._hook_handle.remove()
            self._hook_handle = None

    def __del__(self) -> None:
        self.close()
