"""Utility helpers for the explainable AI module."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import torch
from PIL import Image

from configs.config import CHECKPOINT_PATH, DEVICE, IMAGE_SIZE, OUTPUT_PATH
from inference import load_model
from utils.dataset import MedicalSegmentationDataset

from .gradcam import SegmentationGradCAM
from .heatmap import heatmap_to_image, save_heatmap_image
from .overlay import create_attention_visualization, overlay_heatmap_on_image


XAI_OUTPUT_DIR = OUTPUT_PATH / "xai"
CHECKPOINT_FILE = CHECKPOINT_PATH / "best_model.pth"


@dataclass(frozen=True)
class XAIResult:
    """Store all artifacts generated by the explainability pipeline."""

    image_name: str
    original_image: Image.Image
    predicted_mask: Image.Image
    heatmap_image: Image.Image
    overlay_image: Image.Image
    attention_image: Image.Image
    confidence: float
    highlighted_region: str
    explanation: str
    output_paths: dict[str, Path]
    logits: torch.Tensor | None = None
    probabilities: torch.Tensor | None = None


def get_checkpoint_path() -> Path:
    """Return the default trained checkpoint path."""
    return CHECKPOINT_FILE


def load_xai_model(checkpoint_path: Path | None = None):
    """Load the trained U-Net checkpoint used by the XAI page."""
    checkpoint_path = checkpoint_path or get_checkpoint_path()
    if not checkpoint_path.is_file():
        raise FileNotFoundError(
            f"Trained checkpoint not found at {checkpoint_path}."
        )
    return load_model(checkpoint_path)


def load_image_from_path(image_path: Path) -> Image.Image:
    """Load an RGB image from disk."""
    image = Image.open(image_path).convert("RGB")
    return image


def preprocess_image(image: Image.Image) -> torch.Tensor:
    """Resize and normalize an image for U-Net inference."""
    resized = image.convert("RGB").resize((IMAGE_SIZE, IMAGE_SIZE))
    array = np.asarray(resized, dtype=np.float32) / 255.0
    tensor = torch.from_numpy(array).permute(2, 0, 1).contiguous()
    return tensor


def binary_mask_to_image(mask: np.ndarray | torch.Tensor) -> Image.Image:
    """Convert a binary mask into a grayscale PIL image."""
    if isinstance(mask, torch.Tensor):
        mask = mask.detach().cpu().numpy()

    mask_array = np.squeeze(np.asarray(mask)).astype(np.uint8)
    if mask_array.ndim > 2:
        mask_array = mask_array[0]
    mask_array = (mask_array > 0).astype(np.uint8) * 255
    return Image.fromarray(mask_array, mode="L")


def resolve_prediction_confidence(probabilities: torch.Tensor, mask: torch.Tensor) -> float:
    """Compute a confidence score from the predicted foreground region."""
    probabilities = probabilities.detach()
    mask = mask.detach()
    positive_values = probabilities[mask > 0]
    if positive_values.numel() > 0:
        return float(positive_values.mean().item())
    return float(probabilities.max().item())


def describe_highlight(mask: torch.Tensor) -> str:
    """Create a short description of the highlighted tumor region."""
    mask = mask.detach().cpu()
    foreground_pixels = int((mask > 0).sum().item())
    if foreground_pixels == 0:
        return "No confident tumor region detected."

    total_pixels = int(mask.numel()) or 1
    coverage = (foreground_pixels / total_pixels) * 100.0
    return (
        "Highlighted tumor region covers "
        f"{coverage:.2f}% of the image."
    )


def build_explanation(confidence: float, highlighted_region: str) -> str:
    """Build a beginner-friendly explanation for the attention map."""
    confidence_text = f"{confidence:.2%}"
    return (
        "Grad-CAM highlights the spatial regions that contributed most to the "
        f"U-Net's binary tumor prediction. The model's confidence is "
        f"{confidence_text}. {highlighted_region} "
        "Brighter areas in the heatmap indicate stronger influence on the "
        "final segmentation decision."
    )


def save_xai_outputs(
    heatmap_image: Image.Image,
    overlay_image: Image.Image,
    attention_image: Image.Image,
    output_dir: Path | None = None,
) -> dict[str, Path]:
    """Persist the generated XAI artifacts to disk."""
    output_dir = output_dir or XAI_OUTPUT_DIR
    output_dir.mkdir(parents=True, exist_ok=True)

    heatmap_path = output_dir / "heatmap.png"
    overlay_path = output_dir / "overlay.png"
    attention_path = output_dir / "attention.png"

    save_heatmap_image(heatmap_image, heatmap_path)
    overlay_image.save(overlay_path)
    attention_image.save(attention_path)

    return {
        "heatmap": heatmap_path,
        "overlay": overlay_path,
        "attention": attention_path,
    }


def run_xai_pipeline(
    image_source: Path | str | Image.Image,
    model: Any | None = None,
    output_dir: Path | None = None,
) -> XAIResult:
    """Run the complete explainability pipeline for one MRI image."""
    if model is None:
        model = load_xai_model()

    if isinstance(image_source, (str, Path)):
        image_path = Path(image_source)
        original_image = load_image_from_path(image_path)
        image_name = image_path.name
    else:
        original_image = image_source.convert("RGB")
        image_name = "uploaded_image.png"

    input_tensor = preprocess_image(original_image).unsqueeze(0).to(DEVICE)
    cam = SegmentationGradCAM(model)
    cam_result = cam.generate(input_tensor)

    predicted_mask = binary_mask_to_image(cam_result.predicted_mask)
    heatmap_image = heatmap_to_image(cam_result.heatmap, target_size=original_image.size)
    overlay_image = overlay_heatmap_on_image(original_image, heatmap_image)
    attention_image = create_attention_visualization(
        original_image,
        predicted_mask,
        heatmap_image,
        cam_result.confidence,
    )
    output_paths = save_xai_outputs(
        heatmap_image,
        overlay_image,
        attention_image,
        output_dir=output_dir,
    )

    highlighted_region = describe_highlight(cam_result.predicted_mask)
    explanation = build_explanation(cam_result.confidence, highlighted_region)

    return XAIResult(
        image_name=image_name,
        original_image=original_image,
        predicted_mask=predicted_mask,
        heatmap_image=heatmap_image,
        overlay_image=overlay_image,
        attention_image=attention_image,
        confidence=cam_result.confidence,
        highlighted_region=highlighted_region,
        explanation=explanation,
        output_paths=output_paths,
        logits=cam_result.logits,
        probabilities=cam_result.probabilities,
    )


def load_first_dataset_image() -> tuple[Path, Image.Image]:
    """Load the first available paired dataset image for testing."""
    dataset = MedicalSegmentationDataset()
    if len(dataset) == 0:
        raise ValueError("No paired dataset images were found.")

    image_path, _ = dataset.samples[0]
    return image_path, load_image_from_path(image_path)
